// Stamp a build id into version.js and the service worker's cache name so each
// deploy invalidates the old SW cache. Run last in the codegen pipeline.

import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

export function makeBuildId(d = new Date()) {
  const p = (n) => String(n).padStart(2, '0');
  return (
    `${d.getUTCFullYear()}${p(d.getUTCMonth() + 1)}${p(d.getUTCDate())}-` +
    `${p(d.getUTCHours())}${p(d.getUTCMinutes())}${p(d.getUTCSeconds())}`
  );
}

export function stampVersion(build = makeBuildId()) {
  writeFileSync(
    join(ROOT, 'version.js'),
    `// Generated by tools/stampVersion.js — do not edit by hand.\nexport const BUILD = '${build}';\n`
  );

  const swPath = join(ROOT, 'sw.js');
  if (existsSync(swPath)) {
    let sw = readFileSync(swPath, 'utf8');
    const re = /const CACHE = ['"][^'"]*['"];/;
    if (re.test(sw)) {
      sw = sw.replace(re, `const CACHE = 'birdex-${build}';`);
      writeFileSync(swPath, sw);
      console.log(`[version] BUILD=${build}, sw.js cache → birdex-${build}`);
    } else {
      console.warn('[version] sw.js found but no CACHE constant to replace');
    }
  } else {
    console.log(`[version] BUILD=${build} (sw.js not present yet)`);
  }
  return build;
}

if (process.argv[1]?.endsWith('stampVersion.js')) {
  stampVersion();
}
